<%
'Session.Abandon
Session("UsersID")=""
Session("UsersName")=""
Session("Password")=""
Session("UsersPetName")=""
Session("IsSuperUsers")=""
Session("ListFlag")=""
Session("UsersFlag")=""
Response.Cookies("LQCookies")("UsersID")=""
Response.Cookies("LQCookies")("UsersName")=""
Response.Cookies("LQCookies")("Password")=""
Response.Cookies("LQCookies")("UsersPetName")=""
Response.Cookies("LQCookies")("IsSuperUsers")=""
Response.Cookies("LQCookies")("ListFlag")=""
Response.Cookies("LQCookies")("UsersFlag")=""
Response.Cookies("LQCookies").Expires =Now()-1
Response.Redirect("login.html")
%>