<%
'Session.Abandon
Session("AdminID")=""
Session("AdminName")=""
Session("Password")=""
Session("AdminPetName")=""
Session("IsSuperAdmin")=""
Session("ListFlag")=""
Session("AdminFlag")=""
Response.Cookies("LQ_Cookies")("AdminID")=""
Response.Cookies("LQ_Cookies")("AdminName")=""
Response.Cookies("LQ_Cookies")("Password")=""
Response.Cookies("LQ_Cookies")("AdminPetName")=""
Response.Cookies("LQ_Cookies")("IsSuperAdmin")=""
Response.Cookies("LQ_Cookies")("ListFlag")=""
Response.Cookies("LQ_Cookies")("AdminFlag")=""
Response.Cookies("LQ_Cookies").Expires =Now()-1
Response.Redirect("login.html")
%>